spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: drafter

telegram.bot.token: ${DRAFTIFY_TOKEN:652765743:AAEnbzZBgvHYYk6JKGiVPH5AIQ1zBzBK_BQ}
